[debug] [2020-03-04T01:01:26.942Z] ----------------------------------------------------------------------
[debug] [2020-03-04T01:01:26.958Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve --only functions
[debug] [2020-03-04T01:01:26.958Z] CLI Version:   7.14.0
[debug] [2020-03-04T01:01:26.958Z] Platform:      win32
[debug] [2020-03-04T01:01:26.958Z] Node Version:  v12.16.0
[debug] [2020-03-04T01:01:26.958Z] Time:          Tue Mar 03 2020 20:01:26 GMT-0500 (Eastern Standard Time)
[debug] [2020-03-04T01:01:26.958Z] ----------------------------------------------------------------------
[debug] [2020-03-04T01:01:26.958Z] 
[debug] [2020-03-04T01:01:26.958Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-03-04T01:01:26.958Z] > authorizing via signed-in user
[debug] [2020-03-04T01:01:26.958Z] [iam] checking project socialplatform-801be for permissions ["firebase.projects.get"]
[debug] [2020-03-04T01:01:26.973Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/socialplatform-801be:testIamPermissions  

[debug] [2020-03-04T01:01:27.287Z] <<< HTTP RESPONSE 200
[debug] [2020-03-04T01:01:27.287Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/socialplatform-801be  
 
[debug] [2020-03-04T01:01:27.488Z] <<< HTTP RESPONSE 200
[debug] [2020-03-04T01:01:27.554Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:375:7)
    at Object.<anonymous> (C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\functions.js:21:39)
    at Generator.next (<anonymous>)
    at C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\functions.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\functions.js:4:12)
    at Object.start (C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\functions.js:19:16)
    at C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\index.js:25:40
    at arrayMap (C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\lodash\lodash.js:639:23)
    at Function.map (C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\lodash\lodash.js:9554:14)
    at C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\index.js:24:29
    at Generator.next (<anonymous>)
    at C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\index.js:4:12)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-03-04T04:17:57.777Z] ----------------------------------------------------------------------
[debug] [2020-03-04T04:17:57.780Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve --only functions
[debug] [2020-03-04T04:17:57.780Z] CLI Version:   7.14.0
[debug] [2020-03-04T04:17:57.780Z] Platform:      win32
[debug] [2020-03-04T04:17:57.780Z] Node Version:  v12.16.0
[debug] [2020-03-04T04:17:57.782Z] Time:          Tue Mar 03 2020 23:17:57 GMT-0500 (Eastern Standard Time)
[debug] [2020-03-04T04:17:57.782Z] ----------------------------------------------------------------------
[debug] [2020-03-04T04:17:57.782Z] 
[debug] [2020-03-04T04:17:57.816Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-03-04T04:17:57.817Z] > authorizing via signed-in user
[debug] [2020-03-04T04:17:57.817Z] [iam] checking project socialplatform-801be for permissions ["firebase.projects.get"]
[debug] [2020-03-04T04:17:57.819Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2020-03-04T04:17:57.819Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2020-03-04T04:17:57.993Z] <<< HTTP RESPONSE 200
[debug] [2020-03-04T04:17:58.049Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/socialplatform-801be:testIamPermissions  

[debug] [2020-03-04T04:17:58.363Z] <<< HTTP RESPONSE 200
[debug] [2020-03-04T04:17:58.365Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/socialplatform-801be  
 
[debug] [2020-03-04T04:17:58.629Z] <<< HTTP RESPONSE 200
[debug] [2020-03-04T04:17:58.773Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:375:7)
    at Object.<anonymous> (C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\functions.js:21:39)
    at Generator.next (<anonymous>)
    at C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\functions.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\functions.js:4:12)
    at Object.start (C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\functions.js:19:16)
    at C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\index.js:25:40
    at arrayMap (C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\lodash\lodash.js:639:23)
    at Function.map (C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\lodash\lodash.js:9554:14)
    at C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\index.js:24:29
    at Generator.next (<anonymous>)
    at C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Nassym Morssaoui\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\index.js:4:12)
[error] 
[error] Error: An unexpected error has occurred.
